# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Web"
#loggin_port: 9922

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    start_tag: '[%'
    end_tag:   '%]'

session: "YAML"
session_dir: "/tmp/ns-dancer-sessions"
session_expires: 24 hour

plugins:
  Database:
#    driver: 'mysql'
#    database: 'nsargos'
#    host: 'localhost'
#    port: 3306
#    username: 'root'
#    password: 'cloudops'
#    connection_check_threshold: 30
#    dbi_params:
#        RaiseError: 1
#        AutoCommit: 1
#        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
#    log_queries: 1
  'Cache::CHI': 
    driver: Memory 
    global: 1

php_path: '/usr/bin/php'
web_addr: 'http://uwatch.nices.net:8889'

sso:
  ref: 'http://login.nices.net:8080/?ref='
  sid: 'http://login.nices.net:8080/info?sid='

alarm:
  -
    name: 'sms1'
    label: '短信接收1'
    info: '输入您的手机号码...1'
  -
    name: 'sms2'
    label: '短信接收2'
    info: '输入您的手机号码...2'
  -
    name: 'sms3'
    label: '短信接收3'
    info: '输入您的手机号码...3'
